name: my_chat_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.0.0
  image_picker: ^1.0.7
  record: ^6.0.0
  audioplayers: ^6.5.1
  system_alert_window: ^2.0.3
  path_provider: ^2.1.2
  file_picker: ^10.3.8
  shared_preferences: ^2.2.2
  encrypt: ^5.0.1
  flutter_local_notifications: ^19.5.0
  pointycastle: ^3.9.1
  timezone: ^0.10.0
  collection: ^1.18.0 # For firstWhereOrNull extension method
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
