name: my_chat_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  image_picker: ^1.0.7
  record: ^6.0.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.2
  file_picker: ^10.3.8
  shared_preferences: ^2.2.2
  encrypt: ^5.0.1
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  pointycastle: ^3.9.1
  timezone: ^0.10.0
  collection: ^1.18.0 # For firstWhereOrNull extension method
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
